version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: studiopilates-postgres
    environment:
      POSTGRES_USER: studiopilates
      POSTGRES_PASSWORD: studiopilates
      POSTGRES_DB: studiopilates
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: studiopilates-backend
    environment:
      ENV: dev
      DATABASE_URL: postgresql+psycopg://studiopilates:studiopilates@postgres:5432/studiopilates
      SECRET_KEY: change-me
      CORS_ORIGINS: http://34.67.200.156:3000
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      REFRESH_TOKEN_EXPIRE_DAYS: 7
      EVOLUTION_BASE_URL: ""
      EVOLUTION_TOKEN: ""
      EVOLUTION_INSTANCE: ""
      TOTALPASS_BASE_URL: ""
      TOTALPASS_API_KEY: ""
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/storage:/app/storage
    depends_on:
      - postgres
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    container_name: studiopilates-frontend
    environment:
      NEXT_PUBLIC_API_URL: http://34.67.200.156:8000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    command: npm run dev -- --hostname 0.0.0.0 --port 3000

volumes:
  postgres_data:
